[package]
name = "calq"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
priority-queue = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
